version: '3.4'

services:
  service-a:
    image: service-a:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    depends_on:      
      - vault

  service-b:
    image: service-b:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5001:5001"  
    depends_on:
      - vault
      
  vault:
    image: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: my-root
      VAULT_LOG: 'debug'
      SKIP_SETCAP: 'true'
    ports:      
      - "8200:8200"
  