version: '3.4'

services:
  service-a:
    image: ninjafx/service-a:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - vault

  service-b:
    image: ninjafx/service-b:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5001:5001"
    depends_on:
      - vault

  vault:
    image: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: my-root
      VAULT_LOG: 'debug'
      SKIP_SETCAP: 'true'
    ports:
      - "8200:8200"
  